
sudo: required

services:
  - docker

before_install:
  - docker build -t ayushdock/react-test:latest -f ./client/Dockerfile.dev ./client

script:
  - docker run ayushdock/react-test:latest npm test -- --coverage

after_success:
  -  docker build -t ayushdock/multi-client ./client
  -  docker build -t ayushdock/multi-nginx ./nginx
  -  docker build -t ayushdock/multi-server ./server
  -  docker build -t ayushdock/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and and push them to docker hub
  -  docker push ayushdock/multi-client
  -  docker push ayushdock/multi-nginx
  -  docker push ayushdock/multi-server
  -  docker push ayushdock/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2 
  
  #from aws
  app: multi-docker
  env: Multidocker-env
  
  #from s3 bucket
  bucket-name: elasticbeanstalk-us-east-2-318339392583
  bucket-path: docker-multi 
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
